### ISSUE TITLE
 Implementar exists a nivel de servicio para Disciplina

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/club2023spring#21]
1. **Implementar método `exists` en el servicio:**

   - Agregar un método `exists` en el servicio para verificar la existencia de objetos en la base de datos en función de un ID proporcionado.

2. **Realizar pruebas exhaustivas del servicio con Postman:**

   - Realizar pruebas completas del servicio utilizando Postman para garantizar su correcto funcionamiento. Esto incluye:
     - Prueba POST para agregar nuevos objetos.
     - Prueba PUT para actualizar objetos existentes.
     - Prueba DELETE para eliminar objetos.
     - Prueba GET para recuperar todos los objetos.
     - Prueba GET para recuperar un objeto por su ID.

**Fecha límite:** 22 de Septiembre

**Evidencia:**

Por favor, asegúrate de proporcionar evidencia que respalde la realización exitosa de estas tareas antes de la fecha límite mencionada.

**Comment by SILVIAGONZALEZ1** [comment]
![image](https://github.com/ahumadamob/club2023spring/assets/105380047/e76fb207-f5d3-451d-ad0b-cff34c1f1454)
![image](https://github.com/ahumadamob/club2023spring/assets/105380047/245b1445-3dad-422a-b14a-5afbea02a2f9)
![image](https://github.com/ahumadamob/club2023spring/assets/105380047/eaef61b9-a2c4-4803-8c76-6d83f46f17e9)
![image](https://github.com/ahumadamob/club2023spring/assets/105380047/b89818bd-d84e-4070-bc3c-a88c9f614528)
Hola Profe, el Delete no lo pude hacer por que me da error, ya que la tabla clase unida a la tabla disciplina, me da un error en la Foreing Key, como lo podre resolver?
